[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
  "python -m pip install --user -r requirements_simple.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python3 app_simple.py" 